# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf183c9912e8745fedd9eedb35a043b5df67fb3f3a8d6b498b0722eca5b0e51241900430d56d4fc33692eeec1b452a7feb3bd0e7a2f2e3248efdc690646e244

test:
  secret_key_base: 234ec758ac3010ae70593df078192b36be27014ef9c1efda3cd35b25436b020e44b80b1bbf61956c503d00af181583127bfc687ce7528953ff64adc20791e3e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
